export default {
  "o.plat_1": "O.Plat_1",
  "o.plat_2": "O.Plat_2",
  "o.plat_3": "O.Plat_3",
  "o.plat_4": "O.Plat_4",
  "o.plat_5": "O.Plat_5",
  "o.plat_6": "O.Plat_6",
  "o.plat_7": "O.Plat_7",
  "o.plat_8": "O.Plat_8",
  "o.plat_9": "O.Plat_9",
  "o.plat_10": "O.Plat_10",
  "o.plat_11": "O.Plat_11",
  "o.plat_12": "O.Plat_12",
  "o.plat_13": "O.Plat_13",
  "o.plat_14": "O.Plat_14",
};
